[package]
name = "entity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "entity"
path = "src/mod.rs"

[dependencies]
sea-orm = { version = "1.1.2" }
serde = { version = "1", features = ["derive"] }
